In [1]:
import numpy as np
Arr=np.arange(1,13)
Arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
Arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
Arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
Arr.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
Arr=Arr.reshape(-1,3)
Arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
Arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
Arr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

### Stack

In [13]:
A1=np.arange(12).reshape(3,4)
A1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
A2=np.arange(20).reshape(5,4)
A2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
np.vstack((A1,A2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
A1=np.arange(12).reshape(4,3)
A1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
A2=np.arange(24).reshape(4,6)
A2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
np.hstack((A1,A2))

array([[ 0,  1,  2,  0,  1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 18, 19, 20, 21, 22, 23]])

In [21]:
A=np.arange(1,20)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [22]:
np.sin(A)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [23]:
np.cos(A)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [24]:
np.exp(A)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [25]:
np.log(A)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [26]:
A=np.arange(1,21)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
L=[]
for i in A:
    L.append(i/(i+1))

np.array(L)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      , 0.95238095])

In [34]:
L=[x/(x+1) for x in A]
np.array(L)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      , 0.95238095])

In [35]:
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
fun=np.vectorize(lambda x:x/(x+1))
fun(A)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      , 0.95238095])

In [37]:
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
A=np.linspace(1,100,10)
A

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [44]:
fun(A)

array([0.5       , 0.92307692, 0.95833333, 0.97142857, 0.97826087,
       0.98245614, 0.98529412, 0.98734177, 0.98888889, 0.99009901])

In [46]:
A1 = np.arange(10, 19).reshape(3, 3)
A2 = np.arange(1, 13).reshape(3, 4)

In [48]:
A1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [49]:
A2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
np.dot(A1,A2)

array([[173, 206, 239, 272],
       [218, 260, 302, 344],
       [263, 314, 365, 416]])

In [51]:
A1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [53]:
l=[[32,3,42],[34,56,88],[464,424,24]]
a=np.array(l)
a

array([[ 32,   3,  42],
       [ 34,  56,  88],
       [464, 424,  24]])

In [54]:
np.linalg.inv(a)

array([[ 0.02371333, -0.01169316,  0.0013766 ],
       [-0.02638213,  0.0123419 ,  0.00091509],
       [ 0.00762666,  0.00802751, -0.0011142 ]])

In [58]:
np.linalg.det(a)

-1516784.0000000026

In [59]:
L1=[[1,2],[3,4]]
L2=[[5,6],[7,8]]
A1=np.array(L1)
A2=np.array(L2)

In [62]:
A1

array([[1, 2],
       [3, 4]])

In [63]:
A2

array([[5, 6],
       [7, 8]])

In [64]:
np.vstack((A1,A2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
np.hstack((A1,A2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [66]:
L1=[5,6]

In [68]:
np.column_stack((A1,L1))

array([[1, 2, 5],
       [3, 4, 6]])

In [70]:
print(A1)
print(A2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [71]:
np.concatenate((A1,A2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
np.concatenate((A1,A2),0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [74]:
np.concatenate((A1,A2),1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [75]:
np.concatenate((A1,A2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [76]:
np.concatenate((A1,A2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [82]:
L=[[1,3,5,7,9,11],[2,4,6,8,10,12]]
A1=np.array(L)
A1

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [83]:
np.hsplit(A1,3)

[array([[1, 3],
        [2, 4]]), array([[5, 7],
        [6, 8]]), array([[ 9, 11],
        [10, 12]])]

In [84]:
np.vsplit(A1,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [90]:
A1=np.random.randint(10,99,(4,5))
A1

array([[79, 51, 18, 37, 86],
       [48, 22, 76, 12, 21],
       [16, 39, 26, 21, 75],
       [11, 96, 75, 30, 48]])

In [94]:
A1[...,[3,1,4]]

array([[37, 51, 86],
       [12, 22, 21],
       [21, 39, 75],
       [30, 96, 48]])

In [96]:
A1

array([[79, 51, 18, 37, 86],
       [48, 22, 76, 12, 21],
       [16, 39, 26, 21, 75],
       [11, 96, 75, 30, 48]])

In [95]:
A1[0,...]

array([79, 51, 18, 37, 86])

In [98]:
A1[[3,0],...]

array([[11, 96, 75, 30, 48],
       [79, 51, 18, 37, 86]])

In [108]:
A1[[3,0],...]

array([[11, 96, 75, 30, 48],
       [79, 51, 18, 37, 86]])

In [110]:
A1

array([[79, 51, 18, 37, 86],
       [48, 22, 76, 12, 21],
       [16, 39, 26, 21, 75],
       [11, 96, 75, 30, 48]])

In [113]:
np.sort(A1)

array([[18, 37, 51, 79, 86],
       [12, 21, 22, 48, 76],
       [16, 21, 26, 39, 75],
       [11, 30, 48, 75, 96]])

In [115]:
np.sort(A1,1)

array([[18, 37, 51, 79, 86],
       [12, 21, 22, 48, 76],
       [16, 21, 26, 39, 75],
       [11, 30, 48, 75, 96]])

In [116]:
np.sort(A1,axis=1)

array([[18, 37, 51, 79, 86],
       [12, 21, 22, 48, 76],
       [16, 21, 26, 39, 75],
       [11, 30, 48, 75, 96]])

In [118]:
A1

array([[79, 51, 18, 37, 86],
       [48, 22, 76, 12, 21],
       [16, 39, 26, 21, 75],
       [11, 96, 75, 30, 48]])

In [117]:
np.sort(A1,0)

array([[11, 22, 18, 12, 21],
       [16, 39, 26, 21, 48],
       [48, 51, 75, 30, 75],
       [79, 96, 76, 37, 86]])

In [120]:
np.sort(A1[...,4])

array([21, 48, 75, 86])

In [121]:
L=[("Karan",28),("Arpit",24),("Sam",43),("Akshay",13),("Ankush",69)]
Arr=np.array(L)
Arr

array([['Karan', '28'],
       ['Arpit', '24'],
       ['Sam', '43'],
       ['Akshay', '13'],
       ['Ankush', '69']], dtype='<U6')

In [122]:
np.sort(Arr)

array([['28', 'Karan'],
       ['24', 'Arpit'],
       ['43', 'Sam'],
       ['13', 'Akshay'],
       ['69', 'Ankush']], dtype='<U6')

In [123]:
Arr

array([['Karan', '28'],
       ['Arpit', '24'],
       ['Sam', '43'],
       ['Akshay', '13'],
       ['Ankush', '69']], dtype='<U6')

In [124]:
dt=np.dtype([('name','S10'),('age',int)])

In [125]:
Arr=np.array(L,dtype=dt)
Arr

array([(b'Karan', 28), (b'Arpit', 24), (b'Sam', 43), (b'Akshay', 13),
       (b'Ankush', 69)], dtype=[('name', 'S10'), ('age', '<i4')])

In [126]:
np.sort(Arr,order='name')

array([(b'Akshay', 13), (b'Ankush', 69), (b'Arpit', 24), (b'Karan', 28),
       (b'Sam', 43)], dtype=[('name', 'S10'), ('age', '<i4')])

In [127]:
np.sort(Arr,order='age')

array([(b'Akshay', 13), (b'Arpit', 24), (b'Karan', 28), (b'Sam', 43),
       (b'Ankush', 69)], dtype=[('name', 'S10'), ('age', '<i4')])

In [2]:
data = np.genfromtxt('data.csv', delimiter=',', dtype=str)
data

array([['1', 'Angeli', 'Mapes', 'amapes0@chronoengine.com', 'Male'],
       ['2', 'Petronille', 'Helmke', 'phelmke1@walmart.com', 'Female'],
       ['3', 'Humfrid', 'Sainsberry', 'hsainsberry2@disqus.com', 'Male'],
       ['4', 'Kaja', 'Carnson', 'kcarnson3@amazon.de', 'Female'],
       ['5', 'Basia', 'Narraway', 'bnarraway4@bloomberg.com', 'Female'],
       ['6', 'Hy', 'Robiot', 'hrobiot5@quantcast.com', 'Male'],
       ['7', 'Angelika', 'Pedrocco', 'apedrocco6@quantcast.com',
        'Female'],
       ['8', 'Brigit', 'Olivie', 'bolivie7@so-net.ne.jp', 'Female'],
       ['9', 'Marjorie', 'Coope', 'mcoope8@microsoft.com', 'Female'],
       ['10', 'Demetra', 'Gumey', 'dgumey9@gmpg.org', 'Female'],
       ['11', 'Geneva', 'Vasentsov', 'gvasentsova@wsj.com', 'Female'],
       ['12', 'Llywellyn', 'Bullant', 'lbullantb@sfgate.com', 'Male'],
       ['13', 'Ruperta', 'Dudin', 'rdudinc@dailymotion.com', 'Female'],
       ['14', 'Page', 'Ferrotti', 'pferrottid@mashable.com', 'Female'],
       [

In [3]:
data.shape

(100, 5)

In [4]:
data[...,[1,4]]

array([['Angeli', 'Male'],
       ['Petronille', 'Female'],
       ['Humfrid', 'Male'],
       ['Kaja', 'Female'],
       ['Basia', 'Female'],
       ['Hy', 'Male'],
       ['Angelika', 'Female'],
       ['Brigit', 'Female'],
       ['Marjorie', 'Female'],
       ['Demetra', 'Female'],
       ['Geneva', 'Female'],
       ['Llywellyn', 'Male'],
       ['Ruperta', 'Female'],
       ['Page', 'Female'],
       ['Fara', 'Female'],
       ['Manon', 'Female'],
       ['Josh', 'Male'],
       ['Jarad', 'Male'],
       ['Reinaldos', 'Male'],
       ['Carlene', 'Female'],
       ['Clayson', 'Male'],
       ['Jed', 'Male'],
       ['Matteo', 'Male'],
       ['Carrol', 'Male'],
       ['Flinn', 'Male'],
       ['Any', 'Male'],
       ['Halimeda', 'Female'],
       ['Melissa', 'Female'],
       ['Adrea', 'Female'],
       ['Meaghan', 'Female'],
       ['Baldwin', 'Male'],
       ['Annabelle', 'Female'],
       ['Allyn', 'Female'],
       ['Katerina', 'Female'],
       ['Hedwig', 'Female'],
       [

In [5]:
data[...,range(1,5)]

array([['Angeli', 'Mapes', 'amapes0@chronoengine.com', 'Male'],
       ['Petronille', 'Helmke', 'phelmke1@walmart.com', 'Female'],
       ['Humfrid', 'Sainsberry', 'hsainsberry2@disqus.com', 'Male'],
       ['Kaja', 'Carnson', 'kcarnson3@amazon.de', 'Female'],
       ['Basia', 'Narraway', 'bnarraway4@bloomberg.com', 'Female'],
       ['Hy', 'Robiot', 'hrobiot5@quantcast.com', 'Male'],
       ['Angelika', 'Pedrocco', 'apedrocco6@quantcast.com', 'Female'],
       ['Brigit', 'Olivie', 'bolivie7@so-net.ne.jp', 'Female'],
       ['Marjorie', 'Coope', 'mcoope8@microsoft.com', 'Female'],
       ['Demetra', 'Gumey', 'dgumey9@gmpg.org', 'Female'],
       ['Geneva', 'Vasentsov', 'gvasentsova@wsj.com', 'Female'],
       ['Llywellyn', 'Bullant', 'lbullantb@sfgate.com', 'Male'],
       ['Ruperta', 'Dudin', 'rdudinc@dailymotion.com', 'Female'],
       ['Page', 'Ferrotti', 'pferrottid@mashable.com', 'Female'],
       ['Fara', 'Mannooch', 'fmannooche@bizjournals.com', 'Female'],
       ['Manon', 'Fock

In [137]:
Index=data[...,4]=='Male'
data[Index]

array([['1', 'Angeli', 'Mapes', 'amapes0@chronoengine.com', 'Male'],
       ['3', 'Humfrid', 'Sainsberry', 'hsainsberry2@disqus.com', 'Male'],
       ['6', 'Hy', 'Robiot', 'hrobiot5@quantcast.com', 'Male'],
       ['12', 'Llywellyn', 'Bullant', 'lbullantb@sfgate.com', 'Male'],
       ['17', 'Josh', 'Belle', 'jbelleg@census.gov', 'Male'],
       ['18', 'Jarad', 'Bresner', 'jbresnerh@51.la', 'Male'],
       ['19', 'Reinaldos', 'Gianuzzi', 'rgianuzzii@slideshare.net',
        'Male'],
       ['21', 'Clayson', 'Jennaway', 'cjennawayk@usatoday.com', 'Male'],
       ['22', 'Jed', 'McGilvray', 'jmcgilvrayl@jiathis.com', 'Male'],
       ['23', 'Matteo', 'Zannotelli', 'mzannotellim@canalblog.com',
        'Male'],
       ['24', 'Carrol', 'Antos', 'cantosn@nydailynews.com', 'Male'],
       ['25', 'Flinn', 'Broome', 'fbroomeo@tmall.com', 'Male'],
       ['26', 'Any', 'Lewcock', 'alewcockp@nih.gov', 'Male'],
       ['31', 'Baldwin', "O'Henehan", 'bohenehanu@blogs.com', 'Male'],
       ['36', 'Robb

In [141]:
data[...,4]=='Male'

array([ True, False,  True, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False,  True, False,  True, False,  True,  True,  True,
       False,  True, False, False, False,  True,  True, False, False,
        True, False,  True,  True,  True, False, False, False,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
       False,  True, False, False,  True, False, False,  True, False,
        True, False,  True,  True,  True, False, False, False,  True,
        True, False, False, False,  True, False,  True, False,  True,
        True])

In [142]:
Male=data[data[...,4]=='Male']
len(Male)

47

In [143]:
Female=data[data[...,4]=='Female']
len(Female)

53

In [145]:
np.where(data[...,4]=='Male')

(array([ 0,  2,  5, 11, 16, 17, 18, 20, 21, 22, 23, 24, 25, 30, 35, 38, 40,
        42, 43, 44, 46, 50, 51, 54, 56, 57, 58, 62, 63, 64, 67, 68, 70, 71,
        73, 76, 79, 81, 83, 84, 85, 89, 90, 94, 96, 98, 99], dtype=int64),)

In [146]:
Index=np.where(data[...,4]=='Male')
data[Index]

array([['1', 'Angeli', 'Mapes', 'amapes0@chronoengine.com', 'Male'],
       ['3', 'Humfrid', 'Sainsberry', 'hsainsberry2@disqus.com', 'Male'],
       ['6', 'Hy', 'Robiot', 'hrobiot5@quantcast.com', 'Male'],
       ['12', 'Llywellyn', 'Bullant', 'lbullantb@sfgate.com', 'Male'],
       ['17', 'Josh', 'Belle', 'jbelleg@census.gov', 'Male'],
       ['18', 'Jarad', 'Bresner', 'jbresnerh@51.la', 'Male'],
       ['19', 'Reinaldos', 'Gianuzzi', 'rgianuzzii@slideshare.net',
        'Male'],
       ['21', 'Clayson', 'Jennaway', 'cjennawayk@usatoday.com', 'Male'],
       ['22', 'Jed', 'McGilvray', 'jmcgilvrayl@jiathis.com', 'Male'],
       ['23', 'Matteo', 'Zannotelli', 'mzannotellim@canalblog.com',
        'Male'],
       ['24', 'Carrol', 'Antos', 'cantosn@nydailynews.com', 'Male'],
       ['25', 'Flinn', 'Broome', 'fbroomeo@tmall.com', 'Male'],
       ['26', 'Any', 'Lewcock', 'alewcockp@nih.gov', 'Male'],
       ['31', 'Baldwin', "O'Henehan", 'bohenehanu@blogs.com', 'Male'],
       ['36', 'Robb

In [150]:
np.savetxt("Male.csv",Male,fmt='%s',delimiter=",")

### Task: Count No of Male/Female