In [1]:
import numpy as np
data = np.genfromtxt('data.csv', delimiter=',', dtype=str)
data

array([['1', 'Angeli', 'Mapes', 'amapes0@chronoengine.com', 'Male'],
       ['2', 'Petronille', 'Helmke', 'phelmke1@walmart.com', 'Female'],
       ['3', 'Humfrid', 'Sainsberry', 'hsainsberry2@disqus.com', 'Male'],
       ['4', 'Kaja', 'Carnson', 'kcarnson3@amazon.de', 'Female'],
       ['5', 'Basia', 'Narraway', 'bnarraway4@bloomberg.com', 'Female'],
       ['6', 'Hy', 'Robiot', 'hrobiot5@quantcast.com', 'Male'],
       ['7', 'Angelika', 'Pedrocco', 'apedrocco6@quantcast.com',
        'Female'],
       ['8', 'Brigit', 'Olivie', 'bolivie7@so-net.ne.jp', 'Female'],
       ['9', 'Marjorie', 'Coope', 'mcoope8@microsoft.com', 'Female'],
       ['10', 'Demetra', 'Gumey', 'dgumey9@gmpg.org', 'Female'],
       ['11', 'Geneva', 'Vasentsov', 'gvasentsova@wsj.com', 'Female'],
       ['12', 'Llywellyn', 'Bullant', 'lbullantb@sfgate.com', 'Male'],
       ['13', 'Ruperta', 'Dudin', 'rdudinc@dailymotion.com', 'Female'],
       ['14', 'Page', 'Ferrotti', 'pferrottid@mashable.com', 'Female'],
       [

In [2]:
len(data)

100

In [3]:
data.shape

(100, 5)

In [9]:
print("Total Male:",len(data[data[...,4]=='Male']))
print("Total Female:",len(data[data[...,4]=='Female']))

Total Male: 47
Total Female: 53


In [11]:
M=np.where(data[...,4]=='Male')
F=np.where(data[...,4]=='Female')

In [12]:
data[M]

array([['1', 'Angeli', 'Mapes', 'amapes0@chronoengine.com', 'Male'],
       ['3', 'Humfrid', 'Sainsberry', 'hsainsberry2@disqus.com', 'Male'],
       ['6', 'Hy', 'Robiot', 'hrobiot5@quantcast.com', 'Male'],
       ['12', 'Llywellyn', 'Bullant', 'lbullantb@sfgate.com', 'Male'],
       ['17', 'Josh', 'Belle', 'jbelleg@census.gov', 'Male'],
       ['18', 'Jarad', 'Bresner', 'jbresnerh@51.la', 'Male'],
       ['19', 'Reinaldos', 'Gianuzzi', 'rgianuzzii@slideshare.net',
        'Male'],
       ['21', 'Clayson', 'Jennaway', 'cjennawayk@usatoday.com', 'Male'],
       ['22', 'Jed', 'McGilvray', 'jmcgilvrayl@jiathis.com', 'Male'],
       ['23', 'Matteo', 'Zannotelli', 'mzannotellim@canalblog.com',
        'Male'],
       ['24', 'Carrol', 'Antos', 'cantosn@nydailynews.com', 'Male'],
       ['25', 'Flinn', 'Broome', 'fbroomeo@tmall.com', 'Male'],
       ['26', 'Any', 'Lewcock', 'alewcockp@nih.gov', 'Male'],
       ['31', 'Baldwin', "O'Henehan", 'bohenehanu@blogs.com', 'Male'],
       ['36', 'Robb

In [13]:
data[F]

array([['2', 'Petronille', 'Helmke', 'phelmke1@walmart.com', 'Female'],
       ['4', 'Kaja', 'Carnson', 'kcarnson3@amazon.de', 'Female'],
       ['5', 'Basia', 'Narraway', 'bnarraway4@bloomberg.com', 'Female'],
       ['7', 'Angelika', 'Pedrocco', 'apedrocco6@quantcast.com',
        'Female'],
       ['8', 'Brigit', 'Olivie', 'bolivie7@so-net.ne.jp', 'Female'],
       ['9', 'Marjorie', 'Coope', 'mcoope8@microsoft.com', 'Female'],
       ['10', 'Demetra', 'Gumey', 'dgumey9@gmpg.org', 'Female'],
       ['11', 'Geneva', 'Vasentsov', 'gvasentsova@wsj.com', 'Female'],
       ['13', 'Ruperta', 'Dudin', 'rdudinc@dailymotion.com', 'Female'],
       ['14', 'Page', 'Ferrotti', 'pferrottid@mashable.com', 'Female'],
       ['15', 'Fara', 'Mannooch', 'fmannooche@bizjournals.com', 'Female'],
       ['16', 'Manon', 'Focke', 'mfockef@oracle.com', 'Female'],
       ['20', 'Carlene', 'Willans', 'cwillansj@ed.gov', 'Female'],
       ['27', 'Halimeda', 'Drewet', 'hdrewetq@is.gd', 'Female'],
       ['28', 

In [14]:
len(data[M])

47

In [15]:
len(data[F])

53

In [18]:
c=np.char.count(data[...,4],'Male')
c

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1])

In [19]:
Male=0
Female=0
for i in c:
    if i==1:
        Male=Male+1
    else:
        Female=Female+1
    
print("Male:",Male)
print("Female:",Female)

Male: 47
Female: 53


In [20]:
import collections

In [24]:
collections.Counter(c)

Counter({1: 47, 0: 53})

In [29]:
d=collections.Counter(data[...,4])

In [31]:
d['Male']

47

In [32]:
d['Female']

53

In [34]:
np.count_nonzero(c==1)

47

In [35]:
np.count_nonzero(c==0)

53

In [38]:
(c==1).sum()

47

In [39]:
(c==0).sum()

53

In [41]:
np.bincount(c)

array([53, 47], dtype=int64)

In [43]:
np.char.count(data[...,4],'Male')

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1])

In [45]:
np.sum(data[...,4]=='Male')

47

In [46]:
(data[...,4]=='Male').sum()

47

In [51]:
np.unique(data[...,4])

array(['Female', 'Male'], dtype='<U29')

In [52]:
for i in np.unique(data[...,4]):
    print(i)

Female
Male


In [59]:
data[...,0].astype('int').sum()

5050